name: Port 1
favicon: null
layout_spectrum: 0.98651
typography_spectrum: 0.3474758
title: WGC Portfolio Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#04080a'
    - '#b1c2c2'
    - '#253c4a'
    - '#94abad'
    - '#38648d'
  brandStrength: 0.6875
  lightness: 0.6761547
  saturation: 0.7287863
  rhythmicContrast: 0.7803437
purpose: []
