name: Port 1
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3474758
title: WGC Portfolio Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2056924
  lightness: 0.6761547
  saturation: 0.7287863
  rhythmicContrast: 0.7803437
purpose: []
