name: Port 1
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3474758
title: WGC Portfolio Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2bfbe'
    - '#556265'
    - '#d6e0e8'
    - '#aca59e'
    - '#7b7b79'
  brandStrength: 0.25
  lightness: 0.6761547
  saturation: 0.7287863
  rhythmicContrast: 0.7803437
purpose: []
