typography_spectrum: 0.78679
color:
  brandColors:
    - '#04080a'
    - '#b1c2c2'
    - '#253c4a'
    - '#94abad'
    - '#38648d'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.98651
analytics:
  google: null
  facebook: null
  twitter: null
name: Port 1
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: WGC Portfolio Grid
description: 'Make me, ok!'
purpose: []
